---
title: Apresentação no 14º Engitec
description: 'Falando um pouco sobre desenvolvimento de modelos de IA com um exemplo prático sobre Entidades Nomeadas'
date: '2024-06-05'
author: 'Giliard Godoi'
categories: [engitec, talks]
---

No dia 05 de junho de 2024 eu fiz uma apresentação remota no 14º Encontro do Grupo Interlegis de Tecnologia, o EnGITEC.

O tema do encontro desse ano foi Legislativo Inteligente, e eu fiz uma apresentação sobre Inteligência Artifical, dando uma ideia sobre como é o desenvolvimento de um modelo de Aprendizado de Máquina (*Machine Learning*).

O objetivo principal aqui foi apresentar um exemplo prático de como é feito o desenvolvimento de um modelo supervisionado de IA. Para tanto, eu abordei um problema de Reconhecimento de Entidades Nomeadas em proposições legislativas.

Essa tarefa consiste em identificar de forma automática entidades como nomes de pessoas, organizações, valores monetários, em um documento.

Abaixo, eu disponibilizo os slides da apresentação e o código do projeto apresentado.

- [Slides da apresentação](./GILIARD%20-%20Apresenta%C3%A7%C3%A3o%20EnGITEC.pdf)
- [Repostitório com o código do projeto apresentado](https://github.com/GiliardGodoi/spacy-ner-proposicao-legislativa)