name: Deploy Pelican to GitHub Pages

on:
  push:
    branches:
      - publication  # Substitua pela branch onde você mantém o conteúdo-fonte do site

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código-fonte
        uses: actions/checkout@v4
        with:
          submodules: recursive # Se você usa submódulos Git

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependências do Pelican
        run: |
          python -m pip install --upgrade pip
          python -m pip install "pelican[markdown]" ghp-import beautifulsoup4

      - name: Gerar o site com Pelican
        run: |
          pelican content -o output -s pelicanconf.py

      - name: Publicar no GitHub Pages
        run: |
          ghp-import output -b gh-pages -p
