name: Deploy Pelican to GitHub Pages

on:
  push:
    branches:
      - main  # Substitua pela branch onde você mantém o conteúdo-fonte do site

  # Permite rodar o deploy manualmente
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código-fonte
        uses: actions/checkout@v4
        with:
          submodules: recursive # Se você usa submódulos Git

      - name: Instalar suporte ao locale pt_BR.UTF-8
        run: |
          sudo apt-get update && sudo apt-get install -y locales
          sudo locale-gen pt_BR.UTF-8
          echo "LANG=pt_BR.UTF-8" >> $GITHUB_ENV
          echo "LC_ALL=pt_BR.UTF-8" >> $GITHUB_ENV

      - name: Testar saída do datetime em português
        run: python -c "import locale, datetime; locale.setlocale(locale.LC_TIME, 'pt_BR.UTF-8'); print(datetime.datetime.now().strftime('%A, %d de %B de %Y'))"

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependências do Pelican
        run: |
          python -m pip install --upgrade pip
          python -m pip install "pelican[markdown]" ghp-import beautifulsoup4
          python -m pip install typogrify

      - name: Gerar o site com Pelican
        run: |
          pelican content -o output -s pelicanconf.py

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload dos arquivos para GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: output  # Diretório onde o Pelican gera o site estático

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy para GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

